name: MongoDB Backup to DigitalOcean Spaces
#http://192.241.186.194/

on:
  workflow_dispatch: # Manual trigger
  # schedule:
  #   - cron: '0 */12 * * *' # Uncomment for every 12 hours

jobs:
  backup:
    runs-on: ubuntu-latest

    env:
      VM_HOST: ${{ secrets.VM_HOST }} # Hostname or IP stored as a GitHub secret
      DATE: $(date +'%m-%d-%y')
      BACKUP_PATH: /mongo-data/backups/mongo-backup-$(date +'%m-%d-%y').tar.gz
      BACKUP_FILE: mongo-backup-$(date +'%m-%d-%y').tar.gz
      SPACES_URL: ${{ secrets.SPACES_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install AWS CLI For S3
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VM_HOST }} 
          username: root
          key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
          script: |
              if ! command -v aws &> /dev/null; then
                echo "AWS CLI not found. Installing..."
                curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
                unzip awscliv2.zip
                sudo ./aws/install
              else
                echo "AWS CLI already installed. Skipping installation."
              fi

      - name: rsync Scripts
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr --delete
          path: ./
          remote_path: /tmp/
          remote_host: ${{ secrets.VM_HOST }} 
          remote_user: root
          remote_key: ${{ secrets.DO_SSH_PRIVATE_KEY }} 

      - name: Copy Script and run backup 
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VM_HOST }} 
          username: root
          key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
          script: |
              echo "running script.........................................."  
              chmod +x /tmp/backupDB.sh
              bash /tmp/backupDB.sh
              echo "Script Ran Successfully................................."

      - name: Upload backup to DigitalOcean Spaces
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VM_HOST }} 
          username: root
          key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
          script: |
              # Dynamic date variable
              SPACES_BUCKET="spacebucket3000"
              DATE=$(date +'%m-%d-%y')
              BACKUP_PATH="/mongo-data/backups/mongo-backup-$DATE.tar.gz"
              BACKUP_FILE="./mongo-backup-$DATE.tar.gz"
              aws s3 cp /$BACKUP_PATH s3://$SPACES_BUCKET/ --endpoint-url ${{ secrets.SPACES_URL }}
      
      #- name: Cleanup local backup
      #  run: rm -f ./$BACKUP_FILE
      
      - name: Job Completed
        run: echo "Backup workflow completed successfully."